matrix:
  include:
    - os: linux
      dist: bionic
      language: cpp
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CXX=g++-8 CC=gcc-8
    - os: osx
      osx_image: xcode10.2
      language: cpp
      compiler: clang
    - os: windows
      language: bash
      env: CXX=cl.exe
install:
  - |
    if [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      choco install ninja cmake
    elif [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      export PATH=~/Library/Python/3.7/bin:$PATH
      pip3 install --user ninja cmake
    else
      pip install --user ninja cmake
    fi
script:
  - |
    if [[ $TRAVIS_OS_NAME == 'windows' ]]; then
      cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DARGPARSE_BUILD_TESTS=ON && ninja -C build'
    else
      cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DARGPARSE_BUILD_TESTS=ON && ninja -C build
    fi
  - ./build/test/tests
